import { z } from "zod";

export const memberSchema = z.object({
  id: z.string(),
  clubId: z.string().nullable(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.string().email(),
  phone: z.string().nullable(),
  dateOfBirth: z.string().nullable(),
  gender: z.string().nullable(),
  dwz: z.number().nullable(),
  elo: z.number().nullable(),
  dwzId: z.string().nullable(),
  lichessUsername: z.string().nullable(),
  lichessId: z.string().nullable(),
  isLichessVerified: z.boolean().nullable(),
  lichessAccessToken: z.string().nullable(),
  chesscomUsername: z.string().nullable(),
  fideId: z.string().nullable(),
  status: z.enum(["active", "inactive", "resigned", "honorary"]),
  role: z.enum(["user", "admin", "vorstand", "spielleiter", "jugendwart", "kassenwart", "trainer", "mitglied", "eltern"]),
  joinedAt: z.string().nullable(),
  parentId: z.string().nullable(),
  permissions: z.array(z.string()),
  sepaMandateReference: z.string().nullable(),
  sepaIban: z.string().nullable(),
  sepaBic: z.string().nullable(),
  mandateSignedAt: z.string().nullable(),
  mandateUrl: z.string().nullable(),
  contributionRateId: z.string().nullable(),
  notes: z.string().nullable(),
  medicalNotes: z.string().nullable(),
  emergencyContactName: z.string().nullable(),
  emergencyContactPhone: z.string().nullable(),
  photoConsent: z.boolean().nullable(),
  newsletterConsent: z.boolean().nullable(),
  resultPublicationConsent: z.boolean().nullable(),
  deletionRequestedAt: z.string().nullable(),
  anonymizedAt: z.string().nullable(),
  heritageGameId: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const createMemberSchema = z.object({
  firstName: z.string().min(1, "Vorname ist erforderlich").max(100),
  lastName: z.string().min(1, "Nachname ist erforderlich").max(100),
  email: z.string().email("Ungueltige E-Mail-Adresse"),
  phone: z.string().max(50).optional().nullable(),
  dateOfBirth: z.string().date().optional().nullable().or(z.literal("")),
  gender: z.string().max(20).optional().nullable(),
  dwz: z.coerce.number().int().min(0).max(3000).optional().nullable(),
  elo: z.coerce.number().int().min(0).max(3500).optional().nullable(),
  dwzId: z.string().max(50).optional().nullable(),
  lichessUsername: z.string().max(100).optional().nullable(),
  chesscomUsername: z.string().max(100).optional().nullable(),
  parentId: z.string().optional().nullable(),
  contributionRateId: z.string().optional().nullable(),
  sepaMandateReference: z.string().max(35).optional().nullable(),
  sepaIban: z.string().max(1024).optional().nullable(),
  sepaBic: z.string().max(1024).optional().nullable(),
  mandateSignedAt: z.string().date().optional().nullable().or(z.literal("")),
  mandateUrl: z.string().url().max(1000).optional().nullable().or(z.literal("")),
  notes: z.string().optional().nullable(),
  medicalNotes: z.string().optional().nullable(),
  emergencyContactName: z.string().max(200).optional().nullable(),
  emergencyContactPhone: z.string().max(100).optional().nullable(),
  role: z.enum([
    "admin",
    "vorstand",
    "spielleiter",
    "jugendwart",
    "kassenwart",
    "trainer",
    "mitglied",
    "eltern",
    "user",
  ]).default("mitglied"),
  status: z.enum(["active", "inactive", "resigned", "honorary"]).default("active"),
  photoConsent: z.boolean().optional().nullable(),
  newsletterConsent: z.boolean().optional().nullable(),
  resultPublicationConsent: z.boolean().optional().nullable(),
});

export const updateMemberSchema = createMemberSchema.partial();

export type Member = z.infer<typeof memberSchema>;
export type CreateMemberInput = z.infer<typeof createMemberSchema>;
export type UpdateMemberInput = z.infer<typeof updateMemberSchema>;
